@startuml

[*] --> SinLuz

SinLuz --> Iluminado : aparece fuente de luz
Iluminado --> Sombra : objeto bloquea la luz

Sombra --> Iluminado : objeto deja de bloquear
Iluminado --> SinLuz : desaparece la luz

@enduml